"""Added subsciption id to streamers table

Revision ID: 2db54c9e045d
Revises: 
Create Date: 2025-08-08 20:50:58.847791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db54c9e045d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streamer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_subscription_id', ['subscription_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streamer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###
